spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms
    username: yjx
    password: 130
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.163.com
    username: yangjiexiu2000@163.com
    password: TQCMUUYFVARICFRC
logging:
  config: classpath:config/logback-spring.xml